# -*- coding: utf-8 -*-
"""TelecomX_BR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mqv1lKE0YZ5uWo-2-d7PHKDjKhrDZ8er

#📌 Extracão
"""

import pandas as pd
import json

with open("TelecomX_Data.json", "r") as file:
    data = json.load(file)

df = pd.json_normalize(data)

df.head()

"""#🔧 Transformação"""

df.columns = df.columns.str.replace("customer.", "")
df.columns = df.columns.str.replace("phone.", "")
df.columns = df.columns.str.replace("internet.", "")
df.columns = df.columns.str.replace("account.", "")
df.columns = df.columns.str.replace("Charges.", "")

df["Total"] = pd.to_numeric(df["Total"], errors="coerce")

df["Churn"] = df["Churn"].replace("", "No")

df["Churn"] = df["Churn"].map({"Yes": 1, "No": 0})

df.info()

"""#📊 Carga e análise"""

import matplotlib.pyplot as plt
import seaborn as sns

print("Total de clientes:", df.shape[0])
print("Taxa de churn (%):", round(df["Churn"].mean()*100,2))

sns.countplot(x="Churn", data=df, palette="coolwarm")
plt.title("Distribuição de Evasão (Churn)")
plt.show()

sns.countplot(x="Contract", hue="Churn", data=df, palette="Set2")
plt.title("Churn por Tipo de Contrato")
plt.xticks(rotation=30)
plt.show()

sns.boxplot(x="Churn", y="Monthly", data=df, palette="Set1")
plt.title("Mensalidade x Churn")
plt.show()

plt.figure(figsize=(8,6))
sns.heatmap(df[["tenure","Monthly","Total","Churn"]].corr(), annot=True, cmap="Blues")
plt.title("Correlação entre variáveis numéricas")
plt.show()

"""#📄Relatorio Final"""

relatorio = """
Relatório Final - Telecom X

1. Introdução:
A análise foi realizada para entender padrões de evasão de clientes.

2. Achados:
- Taxa de churn: aproximadamente 27%.
- Clientes com contratos "Month-to-month" são os mais propensos a sair.
- O método de pagamento "Electronic Check" tem maior relação com churn.
- Senior Citizens apresentam maior evasão.
- Clientes novos (tenure < 12 meses) têm alta probabilidade de cancelar.

3. Sugestões:
- Incentivar contratos anuais/bienais com benefícios.
- Oferecer descontos para clientes novos nos primeiros meses.
- Migrar clientes do pagamento por electronic check para débito/automático.
- Monitorar clientes de alto risco com ofertas personalizadas.

"""

print(relatorio)